# azure-pipelines.yml
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  nodeVersion: '20.9.0'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(nodeVersion)
  displayName: 'Install Node.js'

- script: |
    node -v
  displayName: 'Print Node.js version'

- script: |
    npm install
  displayName: 'Install dependencies'

- script: |
    npm run test:nightwatch
  displayName: 'Run Nightwatch tests'
